spring:
  application:
    name: planbow-api
  config:
    import: optional:configserver:${config.server.url}
  ai:
    openai:
      api-key: ${OPENAI.API.KEY}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
server:
  port: 80